project:
  type: website
  output-dir: docs

website:
  title: "Phuong Nguyen"
  description: "Tutorial, blog, and portfolio of Phuong Nguyen"
  site-url: https://phuong-ntl.github.io/
  navbar:
    logo: "/images/logo_phuong.png"
    left: 
      - text: "📝Posts"
        file: index.qmd
      # - text: "{{< fa flask >}} My Course"
      #   file: course.qmd
      - text: "{{< fa address-card >}} About"
        file: about.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/phuong-ntl/
      - icon: github
        href: https://github.com/Phuong-NTL

    pinned: false
  favicon: /images/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "{{< fa regular copyright >}} Copyright 2024, Phuong Nguyen" 

  sidebar:
      - id: articles
        title: "Articles"
        style: "floating"
        collapse-level: 2
        align: left
        contents:
          - section: "🧪 **Power BI Dashboard/Report**"
            contents:
              - text: "1. Financial Dashboard"
                href: posts/financial-dashboard.qmd
          - text: "---"    
format:
  html:
    page-layout: article
    theme: [minty, styles.scss]
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    css: styles.css
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: true