project:
  type: website
  output-dir: docs

website:
  title: "Phuong Nguyen"
  description: "Tutorial, blog, and portfolio of Phuong Nguyen"
  site-url: https://phuong-ntl.github.io/
  navbar:
    logo: "/images/logo-profile/Logo-Phuong-P.png"
    left: 
      - text: "📝Posts"
        file: index.qmd
      # - text: "{{< fa flask >}} My Course"
      #   file: course.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/phuong-ntl/
      - icon: github
        href: https://github.com/Phuong-NTL

    pinned: false
  favicon: /images/logo-profile/favicon.ico
  twitter-card: true
  open-graph: true
  page-footer: "{{< fa regular copyright >}} Copyright 2024, Phuong Nguyen" 

  sidebar:
      - id: articles
        title: "Articles"
        style: "floating"
        collapse-level: 2
        align: left
        contents:
          - section: "📈 **Power BI Dashboard/Report**"
            contents:
              - text: "1. Financial Dashboard"
                href: posts/pbi-tuto-executive-summary-finance-report.qmd
              - text: "2. Reports with Drill-through Pages"
                href: posts/drill_through_page.qmd
          - text: "---" 
          - section: "🚀 **Databricks**"
            contents:
              - text: "1. Get CSV Tables into Databricks"
                href: posts/get_csv_tables_into_databricks.qmd
              - text: "2. Create Sample Azure SQL Server and Database"
                href: posts/create_sample_azure_SQL_server_database.qmd
              - text: "3. Get Table And Visualize Data in Databricks Notebook"
                href: posts/get_table_visualize_data_with_databricks_SQL.qmd                
          - text: "---"
          - section: "📊 **Azure Databricks AI/BI**"
            contents:
              - text: "1. Create a Dashboard by Databricks AI/BI"
                href: posts/create_dashboard_by-databricks_AIBI.qmd
              - text: "2. Connect Databricks Tables to Power BI"
                href: posts/connect_databricks_tables_Power_BI.qmd
              - text: "3. Pipeline of Building a Simple Lakehouse Analytics"
                href: posts/building_simple_Lakehouse_analytics.qmd
          - text: "---"    
format:
  html:
    page-layout: article
    theme: [minty, styles.scss]
    toc: true
    toc-depth: 2
    toc-title: "**Sections**"
    css: styles.css
    html-math-method: katex
    code-overflow: wrap
    highlight-style: github-dark
    code-block-background: true
    link-external-newwindow: true
    embed-resources: true